### ISSUE TITLE
Open Workspace error

### ISSUE THREAD

**Issue by fjchichon** [DiamondLightSource/SuRVoS#102]
>SuRVoS
findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to Arial ('c:\\windows\\fonts\\arial.ttf') with score of 0.050000
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\survos\widgets\slice_viewer.py", line 287, in replot
    layer.draw(self.ax, self.idx, i)
  File "C:\ProgramData\Anaconda3\lib\site-packages\survos\core\layers.py", line 55, in draw
    alpha=self.alpha, interpolation='none')
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 5485, in imshow
    resample=resample, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py", line 824, in __init__
    **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\image.py", line 228, in __init__
    cm.ScalarMappable.__init__(self, norm, cmap)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cm.py", line 203, in __init__
    self.cmap = get_cmap(cmap)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cm.py", line 168, in get_cmap
    % (name, ', '.join(sorted(cmap_d))))
ValueError: Colormap b'gray' is not recognized. Possible values are: Accent, Accent_r, Blues, Blues_r, BrBG, BrBG_r, BuGn, BuGn_r, BuPu, BuPu_r, CMRmap, CMRmap_r, Dark2, Dark2_r, GnBu, GnBu_r, Greens, Greens_r, Greys, Greys_r, OrRd, OrRd_r, Oranges, Oranges_r, PRGn, PRGn_r, Paired, Paired_r, Pastel1, Pastel1_r, Pastel2, Pastel2_r, PiYG, PiYG_r, PuBu, PuBuGn, PuBuGn_r, PuBu_r, PuOr, PuOr_r, PuRd, PuRd_r, Purples, Purples_r, RdBu, RdBu_r, RdGy, RdGy_r, RdPu, RdPu_r, RdYlBu, RdYlBu_r, RdYlGn, RdYlGn_r, Reds, Reds_r, Set1, Set1_r, Set2, Set2_r, Set3, Set3_r, Spectral, Spectral_r, Wistia, Wistia_r, YlGn, YlGnBu, YlGnBu_r, YlGn_r, YlOrBr, YlOrBr_r, YlOrRd, YlOrRd_r, afmhot, afmhot_r, autumn, autumn_r, binary, binary_r, bone, bone_r, brg, brg_r, bwr, bwr_r, cividis, cividis_r, cool, cool_r, coolwarm, coolwarm_r, copper, copper_r, cubehelix, cubehelix_r, flag, flag_r, gist_earth, gist_earth_r, gist_gray, gist_gray_r, gist_heat, gist_heat_r, gist_ncar, gist_ncar_r, gist_rainbow, gist_rainbow_r, gist_stern, gist_stern_r, gist_yarg, gist_yarg_r, gnuplot, gnuplot2, gnuplot2_r, gnuplot_r, gray, gray_r, hot, hot_r, hsv, hsv_r, icefire, icefire_r, inferno, inferno_r, jet, jet_r, magma, magma_r, mako, mako_r, nipy_spectral, nipy_spectral_r, ocean, ocean_r, pink, pink_r, plasma, plasma_r, prism, prism_r, rainbow, rainbow_r, rocket, rocket_r, seismic, seismic_r, spring, spring_r, summer, summer_r, tab10, tab10_r, tab20, tab20_r, tab20b, tab20b_r, tab20c, tab20c_r, terrain, terrain_r, viridis, viridis_r, vlag, vlag_r, winter, winter_r

**Comment by OllyK** [comment]
Hi, this is likely to be a problem with the version of Matplotlib you have. See https://github.com/DiamondLightSource/SuRVoS/issues/71 . Could you roll back to Matplotlib version 3.0.2?
