### ISSUE TITLE
Adding a new label after loading from stored labels

### ISSUE THREAD

**Issue by srikanthnagella** [DiamondLightSource/SuRVoS#51]
- Load a new dataset.
- Create a two new labels
- Predict
- Save and exit
- Load from previous workspace
- Add new label
Traceback (most recent call last):
  File "/apps/anaconda/2.4/envs/ccpi/lib/python3.6/site-packages/survos/plugins/annotations.py", line 515, in on_add_label
    self.save_labels(level)
  File "/apps/anaconda/2.4/envs/ccpi/lib/python3.6/site-packages/survos/plugins/annotations.py", line 630, in save_labels
    parent_labels = self.LBLM.parent_labels(level)))
  File "/apps/anaconda/2.4/envs/ccpi/lib/python3.6/site-packages/survos/core/model.py", line 218, in set_attrs
    f['data'].attrs[k] = v
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/apps/anaconda/2.4/envs/ccpi/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/apps/anaconda/2.4/envs/ccpi/lib/python3.6/site-packages/h5py/_hl/attrs.py", line 171, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1611, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1694, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U10')

**Comment by OllyK** [comment]
Hi Sri,

We're having a similar issue when updating label annotations on SuRVoS 1.1.3 but using Python 2.7:

```
+ Updating labels for [Level 1]
Traceback (most recent call last):
  File "/dls_sw/apps/SuRVoS_2018/lib/python2.7/site-packages/survos/plugins/annotations.py", line 517, in on_add_label
    self.save_labels(level)
  File "/dls_sw/apps/SuRVoS_2018/lib/python2.7/site-packages/survos/plugins/annotations.py", line 632, in save_labels
    parent_labels = self.LBLM.parent_labels(level)))
  File "/dls_sw/apps/SuRVoS_2018/lib/python2.7/site-packages/survos/core/model.py", line 218, in set_attrs
    f['data'].attrs[k] = v
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/dls_sw/apps/SuRVoS_2018/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 93, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/dls_sw/apps/SuRVoS_2018/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 171, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1543, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1565, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1626, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U7')
Aborted (core dumped)
```

Would you suggest that using Python 3.6 is the way to resolve?  I can try next week, I was thinking it could be an ongoing issue with h5py though  

Thanks,

Olly

**Comment by srikanthnagella** [comment]
Hi Olly,

Try 3.6 and if it doesn't work then i will look into the the problem.

Thanks
Sri
