### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by penningav** [DiamondLightSource/SuRVoS#66]
Test and update Windows install.

**Comment by penningav** [comment]
The conda install -c conda-forge -c numba -c ccpi survos
will start, but trying to create a workspace fails with:

C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\survos\widgets\slice_viewer.py:132: MatplotlibDeprecationWarning:
The buttons attribute was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  self.buttons = {}
Traceback (most recent call last):
  File "C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\survos\core\launcher.py", line 54, in on_result
    self.cb(res)
  File "C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\survos\widgets\mainwindow.py", line 290, in on_data_loaded
    self.slice_viewer = SliceViewer()
  File "C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\survos\widgets\slice_viewer.py", line 175, in __init__
    self.layered_canvas.canvas, self, self.locLabel)
  File "C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\survos\widgets\slice_viewer.py", line 55, in __init__
    super(NavigationToolbar, self).__init__(canvas, parent=parent)
  File "C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\matplotlib\backends\backend_qt5.py", line 685, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\matplotlib\backend_bases.py", line 2627, in __init__
    self._init_toolbar()
  File "C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\survos\widgets\slice_viewer.py", line 132, in _init_toolbar
    self.buttons = {}
  File "C:\Users\xsy37748\.conda\envs\survos_min\lib\site-packages\matplotlib\cbook\deprecation.py", line 218, in __set__
    return super().__set__(instance, value)
AttributeError: can't set attribute

**Comment by penningav** [comment]
Hi @srikanthnagella,

I was wondering if you had any advice for how to compile SuRVoS on Windows, any steps you remember needing or certain versions of libraries that were required. Thank you.

Kind regards,

Avery

**Comment by penningav** [comment]
SuRVos1 Compilation

CUDA 10.1
MSVC2017 and CMake

1. python setup.py build_ext
2. Manually add survos_lib to <env>/libs and survos_cuda.dll to <env>/DLLs>
3. python setup.py install --single-version-externally-managed --record=record.txt
4. run "survos"
