### ISSUE TITLE
Survos GUI crush

### ISSUE THREAD

**Issue by Isantos7** [DiamondLightSource/SuRVoS#69]
I'm now segmenting the reconstructed tomograms from the last collection and I' m having some issues when I use it. When I do the coloured annotations with the supervoxel options, I can not add more labels (I already added 2) because when I click in "add label" the screen crushes and Survos is closed. Also sometimes it crushes suddenly. The error that appears on the linux console is attached in this mail.

Have you ever had this error? And also referred to Survos, is there more than one version or Survos 1.0 is the actual one?
Thank you for your help in advance
![Screenshot from 2019-07-03 13-06-38](https://user-images.githubusercontent.com/52568560/60718061-f4b9cd80-9f23-11e9-9046-c719b1b79231.png)
![Screenshot from 2019-07-03 13-06-38](https://user-images.githubusercontent.com/52568560/60718078-03a08000-9f24-11e9-93ef-11dd9e1ab322.png)

Isaac

**Comment by penningav** [comment]
Hi Issac,
Thank you for your bug report! There have been issues with these kinds of crashes before, but in general you should be able to add more than two labels without crashing. May I ask how you installed Survos - was it from the conda channel? Thank you.

Kind regards,

Avery

**Comment by Isantos7** [comment]
Thank you penningav for the fast answer. I think it was installed from the conda-recipe. I think it can be also related with the GPU, which would be the optimal graphic card for SuRvos?
Greetings,

Isaac

**Comment by penningav** [comment]
Hi Issac,

Just checking which way conda was used to install SuRVoS. It could have been via the conda-channel - which is an older version of SuRVoS. From the installation page:
https://diamondlightsource.github.io/SuRVoS/docs/installation/

That would have been this command:

conda install -c conda-forge -c numba -c ccpi survos

On the other hand, if you built SuRVoS from source, the situation would be a bit different, depending on when the source was downloaded . We are working towards a new point release of SuRVoS that should address some of these stability issues. An initial set of bugfixes is on github, so if you were to build it from the current master, your issue could be resolved. The graphics hardware that you run SuRVoS on is an essential ingredient and it would be helpful to know that as well.

Kind regards,

Avery

**Comment by penningav** [comment]
Having had a look, trying to read the workspace that crashed for Issac creates the following error message (on Windows 10):

### volread ###
+ Loading data to memory
+ Normalizing data
+ Calculating data statistics
+ Ready
Traceback (most recent call last):
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\survos\widgets\slice_viewer.py", line 287, in replot
    layer.draw(self.ax, self.idx, i)
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\survos\core\layers.py", line 55, in draw
    alpha=self.alpha, interpolation='none')
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\matplotlib\__init__.py", line 1589, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\matplotlib\cbook\deprecation.py", line 369, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\matplotlib\cbook\deprecation.py", line 369, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\matplotlib\axes\_axes.py", line 5658, in imshow
    resample=resample, **kwargs)
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\matplotlib\image.py", line 857, in __init__
    **kwargs
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\matplotlib\image.py", line 207, in __init__
    cm.ScalarMappable.__init__(self, norm, cmap)
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\matplotlib\cm.py", line 218, in __init__
    self.cmap = get_cmap(cmap)
  File "C:\Users\xsy37748\.conda\envs\survox_deep\lib\site-packages\matplotlib\cm.py", line 183, in get_cmap
    % (name, ', '.join(sorted(cmap_d))))
ValueError: Colormap b'gray' is not recognized. Possible values are: Accent, Accent_r, Blues, Blues_r, BrBG, BrBG_r, BuGn, BuGn_r, BuPu, BuPu_r, CMRmap, CMRmap_r, Dark2, Dark2_r, GnBu, GnBu_r, Greens, Greens_r, Greys, Greys_r, OrRd, OrRd_r, Oranges, Oranges_r, PRGn, PRGn_r, Paired, Paired_r, Pastel1, Pastel1_r, Pastel2, Pastel2_r, PiYG, PiYG_r, PuBu, PuBuGn, PuBuGn_r, PuBu_r, PuOr, PuOr_r, PuRd, PuRd_r, Purples, Purples_r, RdBu, RdBu_r, RdGy, RdGy_r, RdPu, RdPu_r, RdYlBu, RdYlBu_r, RdYlGn, RdYlGn_r, Reds, Reds_r, Set1, Set1_r, Set2, Set2_r, Set3, Set3_r, Spectral, Spectral_r, Wistia, Wistia_r, YlGn, YlGnBu, YlGnBu_r, YlGn_r, YlOrBr, YlOrBr_r, YlOrRd, YlOrRd_r, afmhot, afmhot_r, autumn, autumn_r, binary, binary_r, bone, bone_r, brg, brg_r, bwr, bwr_r, cividis, cividis_r, cool, cool_r, coolwarm, coolwarm_r, copper, copper_r, cubehelix, cubehelix_r, flag, flag_r, gist_earth, gist_earth_r, gist_gray, gist_gray_r, gist_heat, gist_heat_r, gist_ncar, gist_ncar_r, gist_rainbow, gist_rainbow_r, gist_stern, gist_stern_r, gist_yarg, gist_yarg_r, gnuplot, gnuplot2, gnuplot2_r, gnuplot_r, gray, gray_r, hot, hot_r, hsv, hsv_r, icefire, icefire_r, inferno, inferno_r, jet, jet_r, magma, magma_r, mako, mako_r, nipy_spectral, nipy_spectral_r, ocean, ocean_r, pink, pink_r, plasma, plasma_r, prism, prism_r, rainbow, rainbow_r, rocket, rocket_r, seismic, seismic_r, spring, spring_r, summer, summer_r, tab10, tab10_r, tab20, tab20_r, tab20b, tab20b_r, tab20c, tab20c_r, terrain, terrain_r, twilight, twilight_r, twilight_shifted, twilight_shifted_r, viridis, viridis_r, vlag, vlag_r, winter, winter_r
