### ISSUE TITLE
SuRVoS main window will not open with matplotlib 3.1.0

### ISSUE THREAD

**Issue by OllyK** [DiamondLightSource/SuRVoS#71]
When loading a dataset or workspace, SuRVoS will crash with the following error:

```python
Traceback (most recent call last):
  File "/dls_sw/apps/SuRVoS_expt/SuRVoS/survos/widgets/mainwindow.py", line 167, in load_workspace
    if self.main_widget.load_workspace(path):
  File "/dls_sw/apps/SuRVoS_expt/SuRVoS/survos/widgets/mainwindow.py", line 324, in load_workspace
    if self.on_load_workspace():
  File "/dls_sw/apps/SuRVoS_expt/SuRVoS/survos/widgets/mainwindow.py", line 367, in on_load_workspace
    self.on_data_loaded(True)
  File "/dls_sw/apps/SuRVoS_expt/SuRVoS/survos/widgets/mainwindow.py", line 300, in on_data_loaded
    self.slice_viewer = SliceViewer()
  File "/dls_sw/apps/SuRVoS_expt/SuRVoS/survos/widgets/slice_viewer.py", line 175, in __init__
    self.layered_canvas.canvas, self, self.locLabel)
  File "/dls_sw/apps/SuRVoS_expt/SuRVoS/survos/widgets/slice_viewer.py", line 55, in __init__
    super(NavigationToolbar, self).__init__(canvas, parent=parent)
  File "/dls/science/groups/das/SuRVoS/py_envs/survos_expt/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 685, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/dls/science/groups/das/SuRVoS/py_envs/survos_expt/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2627, in __init__
    self._init_toolbar()
  File "/dls_sw/apps/SuRVoS_expt/SuRVoS/survos/widgets/slice_viewer.py", line 132, in _init_toolbar
    self.buttons = {}
  File "/dls/science/groups/das/SuRVoS/py_envs/survos_expt/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 218, in __set__
    return super().__set__(instance, value)
AttributeError: can't set attribute
Aborted
```
This can be prevented by rolling matplotlib back to version 3.0.2.  However, a more permanent solution should be found.

**Comment by fjchichon** [comment]
Thanks
